//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// OVRFLO
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

export const ovrfloAbi = [
  {
    type: 'constructor',
    inputs: [
      { name: 'admin', internalType: 'address', type: 'address' },
      { name: 'treasury', internalType: 'address', type: 'address' },
      { name: '_underlying', internalType: 'address', type: 'address' },
      { name: 'name_', internalType: 'string', type: 'string' },
      { name: 'symbol_', internalType: 'string', type: 'string' },
      { name: '_oracle', internalType: 'address', type: 'address' },
    ],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [],
    name: 'FLASH_FEE_MAX_BPS',
    outputs: [{ name: '', internalType: 'uint16', type: 'uint16' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'MIN_PT_AMOUNT',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'TREASURY_ADDR',
    outputs: [{ name: '', internalType: 'address', type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'WAD',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [
      { name: 'ptToken', internalType: 'address', type: 'address' },
      { name: 'amount', internalType: 'uint256', type: 'uint256' },
    ],
    name: 'claim',
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [{ name: 'ptToken', internalType: 'address', type: 'address' }],
    name: 'claimablePt',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [
      { name: 'market', internalType: 'address', type: 'address' },
      { name: 'ptAmount', internalType: 'uint256', type: 'uint256' },
      { name: 'minToUser', internalType: 'uint256', type: 'uint256' },
    ],
    name: 'deposit',
    outputs: [
      { name: 'toUser', internalType: 'uint256', type: 'uint256' },
      { name: 'toStream', internalType: 'uint256', type: 'uint256' },
      { name: 'streamId', internalType: 'uint256', type: 'uint256' },
    ],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [],
    name: 'factory',
    outputs: [{ name: '', internalType: 'address', type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'flashFeeBps',
    outputs: [{ name: '', internalType: 'uint16', type: 'uint16' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [
      { name: 'ptToken', internalType: 'address', type: 'address' },
      { name: 'amount', internalType: 'uint256', type: 'uint256' },
      { name: 'data', internalType: 'bytes', type: 'bytes' },
    ],
    name: 'flashLoan',
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [],
    name: 'flashLoanPaused',
    outputs: [{ name: '', internalType: 'bool', type: 'bool' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [{ name: '', internalType: 'address', type: 'address' }],
    name: 'marketDepositLimits',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [{ name: '', internalType: 'address', type: 'address' }],
    name: 'marketTotalDeposited',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'oracle',
    outputs: [{ name: '', internalType: 'address', type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'ovrfloToken',
    outputs: [{ name: '', internalType: 'address', type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [
      { name: 'market', internalType: 'address', type: 'address' },
      { name: 'ptAmount', internalType: 'uint256', type: 'uint256' },
    ],
    name: 'previewDeposit',
    outputs: [
      { name: 'toUser', internalType: 'uint256', type: 'uint256' },
      { name: 'toStream', internalType: 'uint256', type: 'uint256' },
      { name: 'feeAmount', internalType: 'uint256', type: 'uint256' },
      { name: 'rateE18', internalType: 'uint256', type: 'uint256' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [{ name: 'market', internalType: 'address', type: 'address' }],
    name: 'previewRate',
    outputs: [{ name: 'rateE18', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [
      { name: 'market', internalType: 'address', type: 'address' },
      { name: 'ptAmount', internalType: 'uint256', type: 'uint256' },
    ],
    name: 'previewStream',
    outputs: [
      { name: 'toUser', internalType: 'uint256', type: 'uint256' },
      { name: 'toStream', internalType: 'uint256', type: 'uint256' },
      { name: 'rateE18', internalType: 'uint256', type: 'uint256' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [{ name: '', internalType: 'address', type: 'address' }],
    name: 'ptToMarket',
    outputs: [{ name: '', internalType: 'address', type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'sablierLL',
    outputs: [
      {
        name: '',
        internalType: 'contract ISablierV2LockupLinear',
        type: 'address',
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [{ name: 'market', internalType: 'address', type: 'address' }],
    name: 'series',
    outputs: [
      { name: 'twapDurationFixed', internalType: 'uint32', type: 'uint32' },
      { name: 'feeBps', internalType: 'uint16', type: 'uint16' },
      { name: 'expiryCached', internalType: 'uint256', type: 'uint256' },
      { name: 'ptToken', internalType: 'address', type: 'address' },
      { name: 'ovrfloToken_', internalType: 'address', type: 'address' },
      { name: 'underlying_', internalType: 'address', type: 'address' },
      { name: 'oracle_', internalType: 'address', type: 'address' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [{ name: 'feeBps', internalType: 'uint16', type: 'uint16' }],
    name: 'setFlashFeeBps',
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [{ name: 'paused', internalType: 'bool', type: 'bool' }],
    name: 'setFlashLoanPaused',
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [
      { name: 'market', internalType: 'address', type: 'address' },
      { name: 'limit', internalType: 'uint256', type: 'uint256' },
    ],
    name: 'setMarketDepositLimit',
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [
      { name: 'market', internalType: 'address', type: 'address' },
      { name: 'pt', internalType: 'address', type: 'address' },
      { name: 'twapDuration', internalType: 'uint32', type: 'uint32' },
      { name: 'expiry', internalType: 'uint256', type: 'uint256' },
      { name: 'feeBps', internalType: 'uint16', type: 'uint16' },
    ],
    name: 'setSeriesApproved',
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [
      { name: 'ptToken', internalType: 'address', type: 'address' },
      { name: 'to', internalType: 'address', type: 'address' },
    ],
    name: 'sweepExcessPt',
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [{ name: 'to', internalType: 'address', type: 'address' }],
    name: 'sweepExcessUnderlying',
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [],
    name: 'underlying',
    outputs: [{ name: '', internalType: 'address', type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [{ name: 'amount', internalType: 'uint256', type: 'uint256' }],
    name: 'unwrap',
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [{ name: 'amount', internalType: 'uint256', type: 'uint256' }],
    name: 'wrap',
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [],
    name: 'wrappedUnderlying',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      { name: 'user', internalType: 'address', type: 'address', indexed: true },
      {
        name: 'market',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
      {
        name: 'ptToken',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
      {
        name: 'ovrfloToken',
        internalType: 'address',
        type: 'address',
        indexed: false,
      },
      {
        name: 'amount',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
      },
    ],
    name: 'Claimed',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      { name: 'user', internalType: 'address', type: 'address', indexed: true },
      {
        name: 'market',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
      {
        name: 'ptAmount',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
      },
      {
        name: 'toUser',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
      },
      {
        name: 'toStream',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
      },
      {
        name: 'streamId',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
      },
    ],
    name: 'Deposited',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'ptToken',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
      { name: 'to', internalType: 'address', type: 'address', indexed: true },
      {
        name: 'amount',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
      },
    ],
    name: 'ExcessSwept',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'underlying',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
      { name: 'to', internalType: 'address', type: 'address', indexed: true },
      {
        name: 'amount',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
      },
    ],
    name: 'ExcessUnderlyingSwept',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'payer',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
      {
        name: 'token',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
      {
        name: 'amount',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
      },
    ],
    name: 'FeeTaken',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'feeBps',
        internalType: 'uint16',
        type: 'uint16',
        indexed: false,
      },
    ],
    name: 'FlashFeeBpsSet',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      { name: 'paused', internalType: 'bool', type: 'bool', indexed: false },
    ],
    name: 'FlashLoanPausedSet',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'borrower',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
      {
        name: 'ptToken',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
      {
        name: 'amount',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
      },
      { name: 'fee', internalType: 'uint256', type: 'uint256', indexed: false },
    ],
    name: 'FlashLoaned',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'market',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
      {
        name: 'limit',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
      },
    ],
    name: 'MarketDepositLimitSet',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'market',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
      {
        name: 'ptToken',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
      {
        name: 'ovrfloToken',
        internalType: 'address',
        type: 'address',
        indexed: false,
      },
      {
        name: 'underlying',
        internalType: 'address',
        type: 'address',
        indexed: false,
      },
      {
        name: 'oracle',
        internalType: 'address',
        type: 'address',
        indexed: false,
      },
      {
        name: 'twapDuration',
        internalType: 'uint32',
        type: 'uint32',
        indexed: false,
      },
      {
        name: 'expiry',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
      },
      {
        name: 'feeBps',
        internalType: 'uint16',
        type: 'uint16',
        indexed: false,
      },
    ],
    name: 'SeriesApproved',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      { name: 'user', internalType: 'address', type: 'address', indexed: true },
      {
        name: 'amount',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
      },
    ],
    name: 'Unwrapped',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      { name: 'user', internalType: 'address', type: 'address', indexed: true },
      {
        name: 'amount',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
      },
    ],
    name: 'Wrapped',
  },
  { type: 'error', inputs: [], name: 'BelowMinPT' },
  { type: 'error', inputs: [], name: 'DepositLimitExceeded' },
  { type: 'error', inputs: [], name: 'ExceedsDeposited' },
  { type: 'error', inputs: [], name: 'FeeTooHigh' },
  { type: 'error', inputs: [], name: 'FlashCallbackFailed' },
  { type: 'error', inputs: [], name: 'FlashPaused' },
  { type: 'error', inputs: [], name: 'InsufficientDeposited' },
  { type: 'error', inputs: [], name: 'InsufficientReserve' },
  { type: 'error', inputs: [], name: 'MarketNotApproved' },
  { type: 'error', inputs: [], name: 'Matured' },
  { type: 'error', inputs: [], name: 'NoExcess' },
  { type: 'error', inputs: [], name: 'NotAdmin' },
  { type: 'error', inputs: [], name: 'NotMatured' },
  { type: 'error', inputs: [], name: 'NothingToStream' },
  { type: 'error', inputs: [], name: 'OracleNotReady' },
  { type: 'error', inputs: [], name: 'PtAlreadyMapped' },
  { type: 'error', inputs: [], name: 'SeriesAlreadyConfigured' },
  { type: 'error', inputs: [], name: 'SlippageExceeded' },
  { type: 'error', inputs: [], name: 'TransferMismatch' },
  { type: 'error', inputs: [], name: 'UnknownPT' },
  { type: 'error', inputs: [], name: 'ZeroAddress' },
  { type: 'error', inputs: [], name: 'ZeroAmount' },
] as const

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// OVRFLOFactory
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

export const ovrfloFactoryAbi = [
  {
    type: 'constructor',
    inputs: [
      { name: '_owner', internalType: 'address', type: 'address' },
      { name: '_oracle', internalType: 'address', type: 'address' },
    ],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [],
    name: 'FEE_MAX_BPS',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'MAX_TWAP_DURATION',
    outputs: [{ name: '', internalType: 'uint32', type: 'uint32' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'MIN_TWAP_DURATION',
    outputs: [{ name: '', internalType: 'uint32', type: 'uint32' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'acceptOwnership',
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [
      { name: 'ovrflo', internalType: 'address', type: 'address' },
      { name: 'market', internalType: 'address', type: 'address' },
      { name: 'twapDuration', internalType: 'uint32', type: 'uint32' },
      { name: 'feeBps', internalType: 'uint16', type: 'uint16' },
    ],
    name: 'addMarket',
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [
      { name: 'ovrflo', internalType: 'address', type: 'address' },
      { name: 'index', internalType: 'uint256', type: 'uint256' },
    ],
    name: 'approvedMarketAt',
    outputs: [{ name: '', internalType: 'address', type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [{ name: 'ovrflo', internalType: 'address', type: 'address' }],
    name: 'approvedMarketCount',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [
      { name: 'ovrflo', internalType: 'address', type: 'address' },
      { name: 'market', internalType: 'address', type: 'address' },
    ],
    name: 'isMarketApproved',
    outputs: [{ name: '', internalType: 'bool', type: 'bool' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'lendingCount',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [{ name: '', internalType: 'address', type: 'address' }],
    name: 'lendingToOvrflo',
    outputs: [{ name: '', internalType: 'address', type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
    name: 'lendings',
    outputs: [{ name: '', internalType: 'address', type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'oracle',
    outputs: [{ name: '', internalType: 'address', type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'ovrfloCount',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [{ name: '', internalType: 'address', type: 'address' }],
    name: 'ovrfloInfo',
    outputs: [
      { name: 'treasury', internalType: 'address', type: 'address' },
      { name: 'underlying', internalType: 'address', type: 'address' },
      { name: 'ovrfloToken', internalType: 'address', type: 'address' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [{ name: '', internalType: 'address', type: 'address' }],
    name: 'ovrfloToLending',
    outputs: [{ name: '', internalType: 'address', type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
    name: 'ovrflos',
    outputs: [{ name: '', internalType: 'address', type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'owner',
    outputs: [{ name: '', internalType: 'address', type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'pendingOwner',
    outputs: [{ name: '', internalType: 'address', type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [
      { name: 'market', internalType: 'address', type: 'address' },
      { name: 'twapDuration', internalType: 'uint32', type: 'uint32' },
    ],
    name: 'prepareOracle',
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [{ name: 'lending', internalType: 'address', type: 'address' }],
    name: 'registerLending',
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [{ name: 'ovrflo', internalType: 'address', type: 'address' }],
    name: 'registerOvrflo',
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [],
    name: 'renounceOwnership',
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [
      { name: 'ovrflo', internalType: 'address', type: 'address' },
      { name: 'feeBps', internalType: 'uint16', type: 'uint16' },
    ],
    name: 'setFlashFeeBps',
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [
      { name: 'ovrflo', internalType: 'address', type: 'address' },
      { name: 'paused', internalType: 'bool', type: 'bool' },
    ],
    name: 'setFlashLoanPaused',
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [
      { name: 'lending', internalType: 'address', type: 'address' },
      { name: 'aprMinBps_', internalType: 'uint16', type: 'uint16' },
      { name: 'aprMaxBps_', internalType: 'uint16', type: 'uint16' },
    ],
    name: 'setLendingAprBounds',
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [
      { name: 'lending', internalType: 'address', type: 'address' },
      { name: 'feeBps_', internalType: 'uint16', type: 'uint16' },
    ],
    name: 'setLendingFee',
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [
      { name: 'lending', internalType: 'address', type: 'address' },
      { name: 'market', internalType: 'address', type: 'address' },
      { name: 'spacing', internalType: 'uint16', type: 'uint16' },
    ],
    name: 'setLendingTickSpacing',
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [
      { name: 'lending', internalType: 'address', type: 'address' },
      { name: 'treasury_', internalType: 'address', type: 'address' },
    ],
    name: 'setLendingTreasury',
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [
      { name: 'ovrflo', internalType: 'address', type: 'address' },
      { name: 'market', internalType: 'address', type: 'address' },
      { name: 'limit', internalType: 'uint256', type: 'uint256' },
    ],
    name: 'setMarketDepositLimit',
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [
      { name: 'ovrflo', internalType: 'address', type: 'address' },
      { name: 'ptToken', internalType: 'address', type: 'address' },
      { name: 'to', internalType: 'address', type: 'address' },
    ],
    name: 'sweepExcessPt',
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [
      { name: 'ovrflo', internalType: 'address', type: 'address' },
      { name: 'to', internalType: 'address', type: 'address' },
    ],
    name: 'sweepExcessUnderlying',
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [{ name: 'newOwner', internalType: 'address', type: 'address' }],
    name: 'transferOwnership',
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [{ name: '', internalType: 'address', type: 'address' }],
    name: 'underlyingToOvrflo',
    outputs: [{ name: '', internalType: 'address', type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'lending',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
      {
        name: 'aprMinBps',
        internalType: 'uint16',
        type: 'uint16',
        indexed: false,
      },
      {
        name: 'aprMaxBps',
        internalType: 'uint16',
        type: 'uint16',
        indexed: false,
      },
    ],
    name: 'LendingAprBoundsSet',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'lending',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
      {
        name: 'feeBps',
        internalType: 'uint16',
        type: 'uint16',
        indexed: false,
      },
    ],
    name: 'LendingFeeSet',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'ovrflo',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
      {
        name: 'lending',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
    ],
    name: 'LendingRegistered',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'lending',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
      {
        name: 'market',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
      {
        name: 'spacing',
        internalType: 'uint16',
        type: 'uint16',
        indexed: false,
      },
    ],
    name: 'LendingTickSpacingSet',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'lending',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
      {
        name: 'treasury',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
    ],
    name: 'LendingTreasurySet',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'ovrflo',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
      {
        name: 'ovrfloToken',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
      {
        name: 'treasury',
        internalType: 'address',
        type: 'address',
        indexed: false,
      },
      {
        name: 'underlying',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
    ],
    name: 'OvrfloRegistered',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'previousOwner',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
      {
        name: 'newOwner',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
    ],
    name: 'OwnershipTransferStarted',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'previousOwner',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
      {
        name: 'newOwner',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
    ],
    name: 'OwnershipTransferred',
  },
  { type: 'error', inputs: [], name: 'AlreadyRegistered' },
  { type: 'error', inputs: [], name: 'FactoryMismatch' },
  { type: 'error', inputs: [], name: 'FeeTooHigh' },
  { type: 'error', inputs: [], name: 'LendingExists' },
  { type: 'error', inputs: [], name: 'MarketExpired' },
  { type: 'error', inputs: [], name: 'OracleCardinalityRequired' },
  { type: 'error', inputs: [], name: 'OracleMismatch' },
  { type: 'error', inputs: [], name: 'OracleNotReady' },
  { type: 'error', inputs: [], name: 'OwnerMismatch' },
  { type: 'error', inputs: [], name: 'SablierMismatch' },
  { type: 'error', inputs: [], name: 'TwapTooLong' },
  { type: 'error', inputs: [], name: 'TwapTooShort' },
  { type: 'error', inputs: [], name: 'UnderlyingAlreadyDeployed' },
  { type: 'error', inputs: [], name: 'UnderlyingMismatch' },
  { type: 'error', inputs: [], name: 'UnknownLending' },
  { type: 'error', inputs: [], name: 'UnknownOvrflo' },
  { type: 'error', inputs: [], name: 'ZeroAddress' },
] as const

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// OVRFLOLending
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

export const ovrfloLendingAbi = [
  {
    type: 'constructor',
    inputs: [
      { name: 'factory_', internalType: 'address', type: 'address' },
      { name: 'core_', internalType: 'address', type: 'address' },
      { name: 'sablier_', internalType: 'address', type: 'address' },
    ],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [],
    name: 'APR_MAX_CEILING',
    outputs: [{ name: '', internalType: 'uint16', type: 'uint16' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'CURSOR_CAP',
    outputs: [{ name: '', internalType: 'uint8', type: 'uint8' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'LAUNCH_APR_BPS',
    outputs: [{ name: '', internalType: 'uint16', type: 'uint16' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'MAX_FEE_BPS',
    outputs: [{ name: '', internalType: 'uint16', type: 'uint16' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'MIN_LIQUIDITY_AMOUNT',
    outputs: [{ name: '', internalType: 'uint128', type: 'uint128' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'MIN_STREAM_AMOUNT',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'UNIT',
    outputs: [{ name: '', internalType: 'uint128', type: 'uint128' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'acceptOwnership',
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [
      { name: 'market', internalType: 'address', type: 'address' },
      { name: 'aprBps', internalType: 'uint16', type: 'uint16' },
      { name: 'maxSteps', internalType: 'uint32', type: 'uint32' },
    ],
    name: 'advanceEpochCursor',
    outputs: [{ name: 'cursor', internalType: 'uint32', type: 'uint32' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [],
    name: 'aprMaxBps',
    outputs: [{ name: '', internalType: 'uint16', type: 'uint16' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'aprMinBps',
    outputs: [{ name: '', internalType: 'uint16', type: 'uint16' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [
      { name: 'market', internalType: 'address', type: 'address' },
      { name: 'aprBps', internalType: 'uint16', type: 'uint16' },
      { name: 'targetBorrow', internalType: 'uint128', type: 'uint128' },
      { name: 'streamId', internalType: 'uint256', type: 'uint256' },
      { name: 'minAcceptable', internalType: 'uint128', type: 'uint128' },
    ],
    name: 'borrow',
    outputs: [{ name: 'loanId', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [
      { name: 'borrower', internalType: 'address', type: 'address' },
      { name: 'index', internalType: 'uint256', type: 'uint256' },
    ],
    name: 'borrowerLoanAt',
    outputs: [{ name: 'loanId', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [{ name: 'borrower', internalType: 'address', type: 'address' }],
    name: 'borrowerLoanCount',
    outputs: [{ name: 'count', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [
      { name: 'loanId', internalType: 'uint256', type: 'uint256' },
      { name: 'positionId', internalType: 'uint256', type: 'uint256' },
      { name: 'amount', internalType: 'uint128', type: 'uint128' },
    ],
    name: 'claim',
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [{ name: 'loanId', internalType: 'uint256', type: 'uint256' }],
    name: 'close',
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [
      { name: 'loanId', internalType: 'uint256', type: 'uint256' },
      { name: 'positionId', internalType: 'uint256', type: 'uint256' },
    ],
    name: 'contributionOf',
    outputs: [
      { name: 'contribution', internalType: 'uint128', type: 'uint128' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'core',
    outputs: [{ name: '', internalType: 'address', type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'factory',
    outputs: [
      {
        name: '',
        internalType: 'contract IOVRFLOFactoryRegistry',
        type: 'address',
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'feeBps',
    outputs: [{ name: '', internalType: 'uint16', type: 'uint16' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [
      { name: 'lender', internalType: 'address', type: 'address' },
      { name: 'index', internalType: 'uint256', type: 'uint256' },
    ],
    name: 'lenderPositionAt',
    outputs: [{ name: 'positionId', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [{ name: 'lender', internalType: 'address', type: 'address' }],
    name: 'lenderPositionCount',
    outputs: [{ name: 'count', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [
      { name: 'market', internalType: 'address', type: 'address' },
      { name: 'aprBps', internalType: 'uint16', type: 'uint16' },
      { name: 'epoch', internalType: 'uint32', type: 'uint32' },
      { name: 'seq', internalType: 'uint64', type: 'uint64' },
    ],
    name: 'loanAt',
    outputs: [{ name: 'loanId', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [{ name: 'loanId', internalType: 'uint256', type: 'uint256' }],
    name: 'loanState',
    outputs: [
      {
        name: 'loan',
        internalType: 'struct OVRFLOLending.Loan',
        type: 'tuple',
        components: [
          { name: 'borrower', internalType: 'address', type: 'address' },
          { name: 'aprBps', internalType: 'uint16', type: 'uint16' },
          { name: 'epoch', internalType: 'uint32', type: 'uint32' },
          { name: 'closed', internalType: 'bool', type: 'bool' },
          { name: 'market', internalType: 'address', type: 'address' },
          { name: 'seq', internalType: 'uint64', type: 'uint64' },
          { name: 'streamId', internalType: 'uint256', type: 'uint256' },
          { name: 'fillStart', internalType: 'uint64', type: 'uint64' },
          { name: 'fillEnd', internalType: 'uint64', type: 'uint64' },
          { name: 'obligation', internalType: 'uint128', type: 'uint128' },
          { name: 'drawn', internalType: 'uint128', type: 'uint128' },
          { name: 'repaid', internalType: 'uint128', type: 'uint128' },
        ],
      },
      { name: 'outstanding', internalType: 'uint128', type: 'uint128' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [{ name: 'loanId', internalType: 'uint256', type: 'uint256' }],
    name: 'loans',
    outputs: [
      { name: 'borrower', internalType: 'address', type: 'address' },
      { name: 'aprBps', internalType: 'uint16', type: 'uint16' },
      { name: 'epoch', internalType: 'uint32', type: 'uint32' },
      { name: 'closed', internalType: 'bool', type: 'bool' },
      { name: 'market', internalType: 'address', type: 'address' },
      { name: 'seq', internalType: 'uint64', type: 'uint64' },
      { name: 'streamId', internalType: 'uint256', type: 'uint256' },
      { name: 'fillStart', internalType: 'uint64', type: 'uint64' },
      { name: 'fillEnd', internalType: 'uint64', type: 'uint64' },
      { name: 'obligation', internalType: 'uint128', type: 'uint128' },
      { name: 'drawn', internalType: 'uint128', type: 'uint128' },
      { name: 'repaid', internalType: 'uint128', type: 'uint128' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [
      { name: 'positionId', internalType: 'uint256', type: 'uint256' },
      { name: 'startSeq', internalType: 'uint64', type: 'uint64' },
      { name: 'maxN', internalType: 'uint256', type: 'uint256' },
    ],
    name: 'loansOf',
    outputs: [
      {
        name: 'entries',
        internalType: 'struct OVRFLOLending.LoanShare[]',
        type: 'tuple[]',
        components: [
          { name: 'loanId', internalType: 'uint256', type: 'uint256' },
          { name: 'contribution', internalType: 'uint128', type: 'uint128' },
          { name: 'claimable', internalType: 'uint128', type: 'uint128' },
        ],
      },
      { name: 'nextSeq', internalType: 'uint64', type: 'uint64' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [{ name: 'data', internalType: 'bytes[]', type: 'bytes[]' }],
    name: 'multicall',
    outputs: [{ name: 'results', internalType: 'bytes[]', type: 'bytes[]' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [],
    name: 'nextLoanId',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'nextPositionId',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'ovrfloToken',
    outputs: [{ name: '', internalType: 'address', type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'owner',
    outputs: [{ name: '', internalType: 'address', type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'pendingOwner',
    outputs: [{ name: '', internalType: 'address', type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [{ name: 'positionId', internalType: 'uint256', type: 'uint256' }],
    name: 'positionState',
    outputs: [
      {
        name: 'position',
        internalType: 'struct OVRFLOLending.Position',
        type: 'tuple',
        components: [
          { name: 'lender', internalType: 'address', type: 'address' },
          { name: 'market', internalType: 'address', type: 'address' },
          { name: 'aprBps', internalType: 'uint16', type: 'uint16' },
          { name: 'epoch', internalType: 'uint32', type: 'uint32' },
          { name: 'leafIndex', internalType: 'uint32', type: 'uint32' },
        ],
      },
      { name: 'intervalStart', internalType: 'uint64', type: 'uint64' },
      { name: 'intervalEnd', internalType: 'uint64', type: 'uint64' },
      { name: 'unfilled', internalType: 'uint128', type: 'uint128' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [{ name: 'positionId', internalType: 'uint256', type: 'uint256' }],
    name: 'positions',
    outputs: [
      { name: 'lender', internalType: 'address', type: 'address' },
      { name: 'market', internalType: 'address', type: 'address' },
      { name: 'aprBps', internalType: 'uint16', type: 'uint16' },
      { name: 'epoch', internalType: 'uint32', type: 'uint32' },
      { name: 'leafIndex', internalType: 'uint32', type: 'uint32' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [{ name: 'loanId', internalType: 'uint256', type: 'uint256' }],
    name: 'proceeds',
    outputs: [{ name: 'amount', internalType: 'uint128', type: 'uint128' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [
      { name: 'loanId', internalType: 'uint256', type: 'uint256' },
      { name: 'positionId', internalType: 'uint256', type: 'uint256' },
    ],
    name: 'received',
    outputs: [{ name: 'amount', internalType: 'uint128', type: 'uint128' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'renounceOwnership',
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [
      { name: 'loanId', internalType: 'uint256', type: 'uint256' },
      { name: 'amount', internalType: 'uint128', type: 'uint128' },
    ],
    name: 'repay',
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [],
    name: 'sablier',
    outputs: [
      {
        name: '',
        internalType: 'contract ISablierV2LockupLinear',
        type: 'address',
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [
      { name: 'aprMinBps_', internalType: 'uint16', type: 'uint16' },
      { name: 'aprMaxBps_', internalType: 'uint16', type: 'uint16' },
    ],
    name: 'setAprBounds',
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [{ name: 'feeBps_', internalType: 'uint16', type: 'uint16' }],
    name: 'setFee',
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [
      { name: 'market', internalType: 'address', type: 'address' },
      { name: 'spacing', internalType: 'uint16', type: 'uint16' },
    ],
    name: 'setTickSpacing',
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [{ name: 'treasury_', internalType: 'address', type: 'address' }],
    name: 'setTreasury',
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [
      { name: 'market', internalType: 'address', type: 'address' },
      { name: 'aprBps', internalType: 'uint16', type: 'uint16' },
      { name: 'amount', internalType: 'uint128', type: 'uint128' },
    ],
    name: 'supply',
    outputs: [{ name: 'positionId', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [{ name: 'market', internalType: 'address', type: 'address' }],
    name: 'tickDepths',
    outputs: [
      {
        name: 'depths',
        internalType: 'struct OVRFLOLending.TickDepth[]',
        type: 'tuple[]',
        components: [
          { name: 'aprBps', internalType: 'uint16', type: 'uint16' },
          { name: 'availableUnits', internalType: 'uint128', type: 'uint128' },
        ],
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [{ name: 'market', internalType: 'address', type: 'address' }],
    name: 'tickSpacing',
    outputs: [{ name: 'spacing', internalType: 'uint16', type: 'uint16' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [
      { name: 'market', internalType: 'address', type: 'address' },
      { name: 'aprBps', internalType: 'uint16', type: 'uint16' },
    ],
    name: 'tickState',
    outputs: [
      { name: 'oldestLiveEpoch', internalType: 'uint32', type: 'uint32' },
      { name: 'currentEpoch', internalType: 'uint32', type: 'uint32' },
      { name: 'availableUnits', internalType: 'uint128', type: 'uint128' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [{ name: 'newOwner', internalType: 'address', type: 'address' }],
    name: 'transferOwnership',
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [],
    name: 'treasury',
    outputs: [{ name: '', internalType: 'address', type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'underlying',
    outputs: [{ name: '', internalType: 'address', type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [{ name: 'positionId', internalType: 'uint256', type: 'uint256' }],
    name: 'withdraw',
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'loanId',
        internalType: 'uint256',
        type: 'uint256',
        indexed: true,
      },
      {
        name: 'borrower',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
      {
        name: 'market',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
      {
        name: 'aprBps',
        internalType: 'uint16',
        type: 'uint16',
        indexed: false,
      },
      { name: 'epoch', internalType: 'uint32', type: 'uint32', indexed: false },
      { name: 'seq', internalType: 'uint64', type: 'uint64', indexed: false },
      {
        name: 'fillStart',
        internalType: 'uint64',
        type: 'uint64',
        indexed: false,
      },
      {
        name: 'fillEnd',
        internalType: 'uint64',
        type: 'uint64',
        indexed: false,
      },
      {
        name: 'actualBorrow',
        internalType: 'uint128',
        type: 'uint128',
        indexed: false,
      },
      {
        name: 'feeAmount',
        internalType: 'uint128',
        type: 'uint128',
        indexed: false,
      },
      {
        name: 'obligation',
        internalType: 'uint128',
        type: 'uint128',
        indexed: false,
      },
      {
        name: 'streamId',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
      },
    ],
    name: 'Borrowed',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'loanId',
        internalType: 'uint256',
        type: 'uint256',
        indexed: true,
      },
      {
        name: 'positionId',
        internalType: 'uint256',
        type: 'uint256',
        indexed: true,
      },
      {
        name: 'amount',
        internalType: 'uint128',
        type: 'uint128',
        indexed: false,
      },
      {
        name: 'receivedTotal',
        internalType: 'uint128',
        type: 'uint128',
        indexed: false,
      },
    ],
    name: 'Claimed',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'loanId',
        internalType: 'uint256',
        type: 'uint256',
        indexed: true,
      },
      {
        name: 'drawn',
        internalType: 'uint128',
        type: 'uint128',
        indexed: false,
      },
    ],
    name: 'Closed',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'market',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
      {
        name: 'aprBps',
        internalType: 'uint16',
        type: 'uint16',
        indexed: false,
      },
      {
        name: 'fromEpoch',
        internalType: 'uint32',
        type: 'uint32',
        indexed: false,
      },
      {
        name: 'toEpoch',
        internalType: 'uint32',
        type: 'uint32',
        indexed: false,
      },
    ],
    name: 'EpochCursorAdvanced',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'market',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
      {
        name: 'aprBps',
        internalType: 'uint16',
        type: 'uint16',
        indexed: false,
      },
      { name: 'epoch', internalType: 'uint32', type: 'uint32', indexed: false },
    ],
    name: 'EpochOpened',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'aprMinBps',
        internalType: 'uint16',
        type: 'uint16',
        indexed: false,
      },
      {
        name: 'aprMaxBps',
        internalType: 'uint16',
        type: 'uint16',
        indexed: false,
      },
    ],
    name: 'LendingAprBoundsSet',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'feeBps',
        internalType: 'uint16',
        type: 'uint16',
        indexed: false,
      },
    ],
    name: 'LendingFeeSet',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'treasury',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
    ],
    name: 'LendingTreasurySet',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'previousOwner',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
      {
        name: 'newOwner',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
    ],
    name: 'OwnershipTransferStarted',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'previousOwner',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
      {
        name: 'newOwner',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
    ],
    name: 'OwnershipTransferred',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'loanId',
        internalType: 'uint256',
        type: 'uint256',
        indexed: true,
      },
      {
        name: 'amount',
        internalType: 'uint128',
        type: 'uint128',
        indexed: false,
      },
      {
        name: 'outstanding',
        internalType: 'uint128',
        type: 'uint128',
        indexed: false,
      },
    ],
    name: 'Repaid',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'positionId',
        internalType: 'uint256',
        type: 'uint256',
        indexed: true,
      },
      {
        name: 'lender',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
      {
        name: 'market',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
      {
        name: 'aprBps',
        internalType: 'uint16',
        type: 'uint16',
        indexed: false,
      },
      { name: 'epoch', internalType: 'uint32', type: 'uint32', indexed: false },
      {
        name: 'leafIndex',
        internalType: 'uint32',
        type: 'uint32',
        indexed: false,
      },
      {
        name: 'amount',
        internalType: 'uint128',
        type: 'uint128',
        indexed: false,
      },
    ],
    name: 'Supplied',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'market',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
      {
        name: 'spacing',
        internalType: 'uint16',
        type: 'uint16',
        indexed: false,
      },
    ],
    name: 'TickSpacingSet',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'positionId',
        internalType: 'uint256',
        type: 'uint256',
        indexed: true,
      },
      {
        name: 'lender',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
      {
        name: 'refund',
        internalType: 'uint128',
        type: 'uint128',
        indexed: false,
      },
      {
        name: 'remainingLeaf',
        internalType: 'uint128',
        type: 'uint128',
        indexed: false,
      },
    ],
    name: 'Withdrawn',
  },
  { type: 'error', inputs: [], name: 'AprTooHigh' },
  { type: 'error', inputs: [], name: 'AtCapacity' },
  { type: 'error', inputs: [], name: 'BadAprBounds' },
  { type: 'error', inputs: [], name: 'BelowMinAcceptable' },
  { type: 'error', inputs: [], name: 'BelowMinimum' },
  { type: 'error', inputs: [], name: 'CancelableStream' },
  { type: 'error', inputs: [], name: 'CliffPresent' },
  { type: 'error', inputs: [], name: 'EmptyTick' },
  { type: 'error', inputs: [], name: 'EpochBacklog' },
  { type: 'error', inputs: [], name: 'EpochMismatch' },
  { type: 'error', inputs: [], name: 'FeeTooHigh' },
  { type: 'error', inputs: [], name: 'InvalidTick' },
  { type: 'error', inputs: [], name: 'LeafMissing' },
  { type: 'error', inputs: [], name: 'LoanClosed' },
  { type: 'error', inputs: [], name: 'LoanMissing' },
  { type: 'error', inputs: [], name: 'MarketNotApproved' },
  { type: 'error', inputs: [], name: 'NoOverlap' },
  { type: 'error', inputs: [], name: 'NodeOverflow' },
  { type: 'error', inputs: [], name: 'NotCovered' },
  { type: 'error', inputs: [], name: 'NotLender' },
  { type: 'error', inputs: [], name: 'NotUnitAligned' },
  { type: 'error', inputs: [], name: 'NothingToClaim' },
  { type: 'error', inputs: [], name: 'NothingToWithdraw' },
  { type: 'error', inputs: [], name: 'PositionMissing' },
  { type: 'error', inputs: [], name: 'RemainingZero' },
  { type: 'error', inputs: [], name: 'RepayExceedsOutstanding' },
  { type: 'error', inputs: [], name: 'SeriesMatured' },
  { type: 'error', inputs: [], name: 'SpacingAlreadySet' },
  { type: 'error', inputs: [], name: 'SpacingUnset' },
  { type: 'error', inputs: [], name: 'TransferMismatch' },
  { type: 'error', inputs: [], name: 'UnknownCore' },
  { type: 'error', inputs: [], name: 'WrongAsset' },
  { type: 'error', inputs: [], name: 'WrongEndTime' },
  { type: 'error', inputs: [], name: 'WrongSender' },
  { type: 'error', inputs: [], name: 'ZeroAddress' },
  { type: 'error', inputs: [], name: 'ZeroAmount' },
  { type: 'error', inputs: [], name: 'ZeroSpacing' },
  { type: 'error', inputs: [], name: 'ZeroSteps' },
  { type: 'error', inputs: [], name: 'ZeroTarget' },
] as const
