[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/"
]
fs_permissions = [
    { access = "read-write", path = "./deployments" }
]
optimizer = true
optimizer_runs = 200
via_ir = false

[rpc_endpoints]
mainnet = "${MAINNET_RPC_URL}"

[etherscan]
unknown_chain = { key = "${TENDERLY_ACCESS_KEY}", chain = 73571, url = "https://virtual.mainnet.us-east.rpc.tenderly.co/db666ddf-0cbc-413c-9f73-fcb2d925db62/verify/etherscan" }

[profile.invariant.invariant]
runs = 500
depth = 40

[invariant]
runs = 25
depth = 10

[fuzz]
runs = 1000

[lint]
exclude_lints = ["mixed-case-function", "mixed-case-variable", "screaming-snake-case-immutable", "screaming-snake-case-const", "unaliased-plain-import", "unwrapped-modifier-logic", "unsafe-typecast", "unused-import"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
