#!/usr/bin/env bash
# write-env.sh — render web/.env.local (or .env.devnet) from a deployment artifact.
#
# The seed scripts (script/seed-local.sh, script/SeedDevnet.s.sol) drop a
# deployments/<network>.json with { chainId, factory, ovrflo, token, lending, stream }.
# This helper reads that artifact, composes the NEXT_PUBLIC_* knobs
# the web app needs, and writes them to web/.env.local (local) or
# web/.env.devnet (devnet), overwriting atomically via a temp file.
#
# Usage:
#   tools/scripts/write-env.sh local
#   tools/scripts/write-env.sh devnet
#
# Env overrides:
#   RPC_URL                          — NEXT_PUBLIC_RPC_URL (default: per-profile)
#   REOWN_PROJECT_ID                 — NEXT_PUBLIC_REOWN_PROJECT_ID
#   DEPLOYMENTS_JSON                 — path override (default: deployments/<network>.json)
#   OUT                              — output path override (default: web/.env.<local|devnet>)

set -euo pipefail

NETWORK="${1:-}"
if [ "$NETWORK" != "local" ] && [ "$NETWORK" != "devnet" ]; then
  echo "write-env: first arg must be 'local' or 'devnet'" >&2
  exit 2
fi

require_cmd() {
  if ! command -v "$1" >/dev/null 2>&1; then
    echo "write-env: '$1' is not on PATH." >&2
    exit 1
  fi
}
require_cmd jq

DEPLOYMENTS_JSON="${DEPLOYMENTS_JSON:-deployments/${NETWORK}.json}"
if [ ! -f "$DEPLOYMENTS_JSON" ]; then
  echo "write-env: $DEPLOYMENTS_JSON not found — run the seed step first." >&2
  exit 1
fi

if ! jq -e '
  .formatVersion == 1 and
  .projectionSchemaVersion == 1 and
  .abiVersion == 1 and
  .freshGeneration == true and
  .chainId == 1 and
  (.factory | type == "string" and test("^0x[0-9a-fA-F]{40}$")) and
  (.factory != "0x0000000000000000000000000000000000000000") and
  (.factoryDeploymentBlock | tostring | test("^(0|[1-9][0-9]*)$")) and
  (.factoryDeploymentBlockHash | type == "string" and test("^0x[0-9a-fA-F]{64}$")) and
  (.lending | type == "string" and test("^0x[0-9a-fA-F]{40}$")) and
  (.lendingDeploymentBlock | tostring | test("^(0|[1-9][0-9]*)$")) and
  (.lendingDeploymentBlockHash | type == "string" and test("^0x[0-9a-fA-F]{64}$")) and
  (.stream | type == "string" and test("^0x[0-9a-fA-F]{40}$")) and
  (.stream != "0x0000000000000000000000000000000000000000")
' "$DEPLOYMENTS_JSON" >/dev/null; then
  echo "write-env: $DEPLOYMENTS_JSON is not a verified fresh-generation v1 artifact." >&2
  echo "write-env: regenerate it with write-deployment-artifact.mjs before building the UI." >&2
  exit 1
fi

FACTORY=$(jq -r '.factory' "$DEPLOYMENTS_JSON")
CHAIN_ID=$(jq -r '.chainId' "$DEPLOYMENTS_JSON")
FACTORY_BLOCK=$(jq -r '.factoryDeploymentBlock' "$DEPLOYMENTS_JSON")
FACTORY_BLOCK_HASH=$(jq -r '.factoryDeploymentBlockHash' "$DEPLOYMENTS_JSON")
OVRFLO=$(jq -r '.ovrflo' "$DEPLOYMENTS_JSON")
LENDING=$(jq -r '.lending' "$DEPLOYMENTS_JSON")
LENDING_BLOCK=$(jq -r '.lendingDeploymentBlock' "$DEPLOYMENTS_JSON")
LENDING_BLOCK_HASH=$(jq -r '.lendingDeploymentBlockHash' "$DEPLOYMENTS_JSON")
STREAM=$(jq -r '.stream' "$DEPLOYMENTS_JSON")
PROJECTION_SCHEMA_VERSION=$(jq -r '.projectionSchemaVersion' "$DEPLOYMENTS_JSON")
ABI_VERSION=$(jq -r '.abiVersion' "$DEPLOYMENTS_JSON")

if [ "$CHAIN_ID" != "1" ]; then
  echo "write-env: deployment chainId is $CHAIN_ID, not 1. The UI rejects non-mainnet." >&2
  exit 1
fi

case "$NETWORK" in
  local)
    DEFAULT_RPC="http://127.0.0.1:8545"
    # Claim All's verifier requires a provider URL string-distinct from the
    # historical one (useProjectionSync's verifierRpcUrl). Locally there is
    # one Anvil, so publish it under a second hostname alias; corroboration
    # semantics are exercised, provider independence is not (local-only).
    DEFAULT_RPC_FALLBACKS="http://localhost:8545"
    OUT_DEFAULT="web/.env.local"
    ;;
  devnet)
    # Intentionally empty — operator must supply TENDERLY_RPC_URL via RPC_URL.
    DEFAULT_RPC=""
    OUT_DEFAULT="web/.env.devnet"
    ;;
esac

RPC_URL="${RPC_URL:-$DEFAULT_RPC}"
RPC_FALLBACK_URLS="${RPC_FALLBACK_URLS:-${DEFAULT_RPC_FALLBACKS:-}}"
HISTORICAL_RPC_URL="${HISTORICAL_RPC_URL:-$RPC_URL}"
REOWN_PROJECT_ID="${REOWN_PROJECT_ID:-}"
OUT="${OUT:-$OUT_DEFAULT}"

if [ "$NETWORK" = "devnet" ] && [ -z "$RPC_URL" ]; then
  echo "write-env: RPC_URL is required for devnet (Tenderly Virtual Testnet URL)." >&2
  exit 1
fi

mkdir -p "$(dirname "$OUT")"
TMP=$(mktemp "${OUT}.XXXXXX")
trap 'rm -f "$TMP"' EXIT

{
  echo "# Generated by tools/scripts/write-env.sh ($NETWORK profile)."
  echo "# Regenerate: npm run env:write:$NETWORK"
  echo "NEXT_PUBLIC_RUNTIME_PROFILE=local"
  echo "NEXT_PUBLIC_CHAIN_ID=$CHAIN_ID"
  echo "NEXT_PUBLIC_OVRFLO_FACTORY=$FACTORY"
  echo "NEXT_PUBLIC_FACTORY_DEPLOYMENT_BLOCK=$FACTORY_BLOCK"
  echo "NEXT_PUBLIC_FACTORY_DEPLOYMENT_BLOCK_HASH=$FACTORY_BLOCK_HASH"
  echo "NEXT_PUBLIC_OVRFLO_ADDRESS=$OVRFLO"
  echo "NEXT_PUBLIC_OVRFLO_LENDING=$LENDING"
  echo "NEXT_PUBLIC_LENDING_DEPLOYMENT_BLOCK=$LENDING_BLOCK"
  echo "NEXT_PUBLIC_LENDING_DEPLOYMENT_BLOCK_HASH=$LENDING_BLOCK_HASH"
  echo "NEXT_PUBLIC_SABLIER_LOCKUP_ADDRESS=$STREAM"
  echo "NEXT_PUBLIC_PROJECTION_SCHEMA_VERSION=$PROJECTION_SCHEMA_VERSION"
  echo "NEXT_PUBLIC_ABI_VERSION=$ABI_VERSION"
  if [ -n "$RPC_URL" ]; then
    echo "NEXT_PUBLIC_RPC_URL=$RPC_URL"
  fi
  if [ -n "$RPC_FALLBACK_URLS" ]; then
    echo "NEXT_PUBLIC_RPC_FALLBACK_URLS=$RPC_FALLBACK_URLS"
  fi
  if [ -n "$HISTORICAL_RPC_URL" ]; then
    echo "NEXT_PUBLIC_HISTORICAL_RPC_URL=$HISTORICAL_RPC_URL"
  fi
  if [ -n "$REOWN_PROJECT_ID" ]; then
    echo "NEXT_PUBLIC_REOWN_PROJECT_ID=$REOWN_PROJECT_ID"
  else
    echo "# NEXT_PUBLIC_REOWN_PROJECT_ID must be set before running the UI."
    echo "# NEXT_PUBLIC_REOWN_PROJECT_ID="
  fi
} > "$TMP"

mv "$TMP" "$OUT"
trap - EXIT

echo "write-env: wrote $OUT"
echo "           factory=$FACTORY@$FACTORY_BLOCK  stream=$STREAM  rpc=${RPC_URL:-<unset>}"
