#!/usr/bin/env bash
# write-env.sh — render web/.env.local (or .env.devnet) from a deployment artifact.
#
# The seed scripts (script/seed-local.sh, script/SeedDevnet.s.sol) drop a
# deployments/<network>.json with { chainId, factory, ovrflo, token, devWallet }.
# This helper reads that artifact, composes the seven NEXT_PUBLIC_* knobs
# the web app needs, and writes them to web/.env.local (local) or
# web/.env.devnet (devnet), overwriting atomically via a temp file.
#
# Usage:
#   tools/scripts/write-env.sh local
#   tools/scripts/write-env.sh devnet
#
# Env overrides:
#   RPC_URL                          — NEXT_PUBLIC_RPC_URL (default: per-profile)
#   REOWN_PROJECT_ID                 — NEXT_PUBLIC_REOWN_PROJECT_ID
#   SABLIER_INDEXER_URL              — NEXT_PUBLIC_SABLIER_INDEXER_URL
#                                      (default: localhost:8080 for local, unset = hosted for devnet)
#   DEPLOYMENTS_JSON                 — path override (default: deployments/<network>.json)
#   OUT                              — output path override (default: web/.env.<local|devnet>)

set -euo pipefail

NETWORK="${1:-}"
if [ "$NETWORK" != "local" ] && [ "$NETWORK" != "devnet" ]; then
  echo "write-env: first arg must be 'local' or 'devnet'" >&2
  exit 2
fi

require_cmd() {
  if ! command -v "$1" >/dev/null 2>&1; then
    echo "write-env: '$1' is not on PATH." >&2
    exit 1
  fi
}
require_cmd jq

DEPLOYMENTS_JSON="${DEPLOYMENTS_JSON:-deployments/${NETWORK}.json}"
if [ ! -f "$DEPLOYMENTS_JSON" ]; then
  echo "write-env: $DEPLOYMENTS_JSON not found — run the seed step first." >&2
  exit 1
fi

FACTORY=$(jq -r '.factory'   "$DEPLOYMENTS_JSON")
CHAIN_ID=$(jq -r '.chainId'  "$DEPLOYMENTS_JSON")

if [ "$CHAIN_ID" != "1" ]; then
  echo "write-env: deployment chainId is $CHAIN_ID, not 1. The UI rejects non-mainnet." >&2
  exit 1
fi

case "$NETWORK" in
  local)
    DEFAULT_RPC="http://127.0.0.1:8545"
    # Local Envio Hasura endpoint from `envio dev` — see tools/envio/README.md.
    DEFAULT_INDEXER="http://localhost:8080/v1/graphql"
    OUT_DEFAULT="web/.env.local"
    ;;
  devnet)
    # Intentionally empty — operator must supply TENDERLY_RPC_URL via RPC_URL.
    DEFAULT_RPC=""
    # Empty => UI falls back to SABLIER_INDEXER_URL_DEFAULT (hosted).
    DEFAULT_INDEXER=""
    OUT_DEFAULT="web/.env.devnet"
    ;;
esac

RPC_URL="${RPC_URL:-$DEFAULT_RPC}"
SABLIER_INDEXER_URL="${SABLIER_INDEXER_URL:-$DEFAULT_INDEXER}"
REOWN_PROJECT_ID="${REOWN_PROJECT_ID:-}"
OUT="${OUT:-$OUT_DEFAULT}"

if [ "$NETWORK" = "devnet" ] && [ -z "$RPC_URL" ]; then
  echo "write-env: RPC_URL is required for devnet (Tenderly Virtual Testnet URL)." >&2
  exit 1
fi

mkdir -p "$(dirname "$OUT")"
TMP=$(mktemp "${OUT}.XXXXXX")
trap 'rm -f "$TMP"' EXIT

{
  echo "# Generated by tools/scripts/write-env.sh ($NETWORK profile)."
  echo "# Regenerate: npm run env:write:$NETWORK"
  echo "NEXT_PUBLIC_CHAIN_ID=$CHAIN_ID"
  echo "NEXT_PUBLIC_OVRFLO_FACTORY=$FACTORY"
  if [ -n "$RPC_URL" ]; then
    echo "NEXT_PUBLIC_RPC_URL=$RPC_URL"
  fi
  if [ -n "$REOWN_PROJECT_ID" ]; then
    echo "NEXT_PUBLIC_REOWN_PROJECT_ID=$REOWN_PROJECT_ID"
  else
    echo "# NEXT_PUBLIC_REOWN_PROJECT_ID must be set before running the UI."
    echo "# NEXT_PUBLIC_REOWN_PROJECT_ID="
  fi
  if [ -n "$SABLIER_INDEXER_URL" ]; then
    echo "NEXT_PUBLIC_SABLIER_INDEXER_URL=$SABLIER_INDEXER_URL"
  fi
} > "$TMP"

mv "$TMP" "$OUT"
trap - EXIT

echo "write-env: wrote $OUT"
echo "           factory=$FACTORY  rpc=${RPC_URL:-<wagmi default>}  indexer=${SABLIER_INDEXER_URL:-<hosted default>}"
