// SPDX-License-Identifier: MIT
pragma solidity >=0.6.2 <0.9.0;

import {Test} from "forge-std/Test.sol";
import {Handlers} from "./handlers/Handlers.sol";

/// @notice Contract to be used for quick testing with Foundry
contract FoundryTester is Test, Handlers {
    modifier asActor() override {
        vm.startPrank(actor);
        _;
        vm.stopPrank();
    }

    function setUp() public {
        setup();
    }

    // ── Violation Repros (auto-generated by Step 11) ──────────────────
    // Each test_repro_* function below replays a shrunk fuzzer call
    // sequence that violated a property. Run all with:
    //   forge test --match-contract FoundryTester -vvv

    /// @notice Smoke test: verifies setup deployed all contracts and actors are funded
    function test_smoke_setup() public view {
        assertNotEq(address(vault), address(0), "vault deployed");
        assertNotEq(address(ovrfloToken), address(0), "ovrfloToken deployed");
        assertNotEq(address(lending), address(0), "lending deployed");
        assertGt(underlying.balanceOf(actors[0]), 0, "actor[0] funded with underlying");
        assertGt(ptToken.balanceOf(actors[0]), 0, "actor[0] funded with PT");
    }
}
