// SPDX-License-Identifier: MIT
pragma solidity >=0.6.2 <0.9.0;

import {Test} from "forge-std/Test.sol";
import {console} from "forge-std/console.sol";
import {Handlers} from "./handlers/Handlers.sol";

/// @notice Contract to be used for quick testing with Foundry
contract FoundryTester is Test, Handlers {
    // No `asActor` override: Base's modifier must run here too, or the ghost
    // accounting is dead under Foundry and a fuzzer-found ghost-backed violation
    // will not replay faithfully as a test_repro_* sequence.

    function setUp() public {
        setup();
    }

    // forge test --match-test test_sequence -vvv
    function test_sequence() public {
        // Add here call sequence to Handler's functions to reproduce failing property
    }

    /// @notice End-to-end sanity gate for Step 6/7: deposit -> supply -> borrow must
    ///         all succeed and produce nonzero ids, or the harness is broken and Step 8
    ///         coverage will be zero.
    function test_sanity_depositSupplyBorrow() public {
        // 1. An OVRFLO deposit creates the Sablier collateral stream `borrow` needs.
        uint256 ptAmount = 1_000e18;
        ovrflo_deposit(market, ptAmount, 0);
        assertGt(streamIds.length, 0, "deposit did not record a stream id");
        uint256 streamId = streamIds[streamIds.length - 1];

        // 2. A lender supplies liquidity at a valid, spacing-aligned tick.
        uint128 supplyAmount = 10e18;
        lending_supply(market, 0, supplyAmount);
        assertGt(positionIds.length, 0, "supply did not record a position id");

        // 3. The same actor borrows against the freshly-deposited stream.
        lending_borrow(market, 0, 1e18, streamId, 0);
        assertGt(loanIds.length, 0, "borrow did not record a loan id");

        console.log("sanity: streamId =", streamId);
        console.log("sanity: positionId =", positionIds[positionIds.length - 1]);
        console.log("sanity: loanId =", loanIds[loanIds.length - 1]);
    }

    /// @notice SC10: mock `balanceOf` matches the ownership-filtered mirror.
    function test_sc10_actorStreamEnumeration() public {
        property_actorStreamEnumeration();
        test_sanity_depositSupplyBorrow();
        property_actorStreamEnumeration();
    }

    // ── Violation Repros (auto-generated by Step 11) ──────────────────
    // Each test_repro_* function below replays a shrunk fuzzer call
    // sequence that violated a property. Run all with:
    //   forge test --match-contract FoundryTester -vvv
}
