// Event handlers for SablierV2LockupLinear v1.1 on mainnet.
// Modeled after sablier-labs/indexers@v5.0.0 but trimmed to the single
// contract OVRFLO integrates with. See tools/envio/NOTICE.md for the pin.
//
// The `SablierV2LockupLinear` symbol below is generated by `envio codegen`
// from config.yaml — the import path is the standard Envio convention.
import { SablierV2LockupLinear } from "generated";

type Address = string;

const ZERO_ADDRESS: Address = "0x0000000000000000000000000000000000000000";

function streamId(chainId: number | bigint, contract: Address, tokenId: bigint): string {
  return `${contract.toLowerCase()}-${chainId.toString()}-${tokenId.toString()}`;
}

function assetId(chainId: number | bigint, asset: Address): string {
  return `asset-${chainId.toString()}-${asset.toLowerCase()}`;
}

// Asset metadata (name/symbol/decimals) isn't available from the event
// payload. For the OVRFLO local loop we only stream ovrfloTokens, which
// are always 18-decimal ERC20s with known symbols — the UI's token label
// helper resolves these anyway. Default to placeholders; downstream
// rendering uses on-chain balanceOf/symbol calls, not these fields.
const DEFAULT_ASSET_DECIMALS = 18n;
const DEFAULT_ASSET_SYMBOL = "OVRFLO";
const DEFAULT_ASSET_NAME = "OVRFLO token";

SablierV2LockupLinear.CreateLockupLinearStream.handler(async ({ event, context }) => {
  const contract = event.srcAddress.toLowerCase();
  const chainId = BigInt(event.chainId);
  const tokenId = event.params.streamId;

  const assetKey = assetId(chainId, event.params.asset);
  const existingAsset = await context.Asset.get(assetKey);
  if (!existingAsset) {
    context.Asset.set({
      id: assetKey,
      address: event.params.asset.toLowerCase(),
      chainId,
      decimals: DEFAULT_ASSET_DECIMALS,
      name: DEFAULT_ASSET_NAME,
      symbol: DEFAULT_ASSET_SYMBOL,
    });
  }

  const depositAmount = event.params.amounts.deposit;

  context.LockupStream.set({
    id: streamId(chainId, contract, tokenId),
    chainId,
    tokenId,
    contract,
    category: "LockupLinear",
    recipient: event.params.recipient.toLowerCase(),
    sender: event.params.sender.toLowerCase(),
    funder: event.params.funder.toLowerCase(),
    asset_id: assetKey,
    cancelable: event.params.cancelable,
    canceled: false,
    depleted: false,
    depositAmount,
    intactAmount: depositAmount,
    withdrawnAmount: 0n,
    startTime: BigInt(event.params.range.start),
    endTime: BigInt(event.params.range.end),
    cliffTime: BigInt(event.params.range.cliff),
    transferable: event.params.transferable,
  });
});

SablierV2LockupLinear.CancelLockupStream.handler(async ({ event, context }) => {
  const contract = event.srcAddress.toLowerCase();
  const chainId = BigInt(event.chainId);
  const id = streamId(chainId, contract, event.params.streamId);
  const stream = await context.LockupStream.get(id);
  if (!stream) return;

  // recipientAmount = amount still owed to recipient (i.e., vested-but-unwithdrawn).
  // The sender claws back senderAmount. After Cancel the stream cannot be
  // unvoided, but recipient can still withdrawMax any vested portion.
  context.LockupStream.set({
    ...stream,
    canceled: true,
    cancelable: false,
    intactAmount: event.params.recipientAmount,
  });
});

SablierV2LockupLinear.WithdrawFromLockupStream.handler(async ({ event, context }) => {
  const contract = event.srcAddress.toLowerCase();
  const chainId = BigInt(event.chainId);
  const id = streamId(chainId, contract, event.params.streamId);
  const stream = await context.LockupStream.get(id);
  if (!stream) return;

  const withdrawn = stream.withdrawnAmount + event.params.amount;
  const intact = stream.intactAmount > event.params.amount
    ? stream.intactAmount - event.params.amount
    : 0n;

  context.LockupStream.set({
    ...stream,
    withdrawnAmount: withdrawn,
    intactAmount: intact,
    depleted: intact === 0n,
  });
});

SablierV2LockupLinear.RenounceLockupStream.handler(async ({ event, context }) => {
  const contract = event.srcAddress.toLowerCase();
  const chainId = BigInt(event.chainId);
  const id = streamId(chainId, contract, event.params.streamId);
  const stream = await context.LockupStream.get(id);
  if (!stream) return;

  context.LockupStream.set({ ...stream, cancelable: false });
});

// Transfer updates `recipient` so queries filtered by recipient pick up
// NFTs that were transferred post-create. This is the fix documented in
// docs/solutions/integration-issues/transferred-sablier-nfts-invisible-WebUI-20260421.md.
SablierV2LockupLinear.Transfer.handler(async ({ event, context }) => {
  const contract = event.srcAddress.toLowerCase();
  const chainId = BigInt(event.chainId);
  const id = streamId(chainId, contract, event.params.tokenId);
  const stream = await context.LockupStream.get(id);
  if (!stream) return;

  // The ERC721 mint emits Transfer(from=0x0, to=recipient). CreateLockupLinearStream
  // is emitted in the same tx and already sets `recipient`; skip the mint transfer
  // to avoid clobbering the recipient with a no-op write against a just-created row.
  if (event.params.from.toLowerCase() === ZERO_ADDRESS) return;

  context.LockupStream.set({
    ...stream,
    recipient: event.params.to.toLowerCase(),
  });
});
