import type { NextConfig } from "next";
import path from "node:path";

// Note (R19, R20): this config intentionally does NOT set security
// headers. Next's `headers()` API is a no-op under `output: "export"` —
// real CSP ships as deploy-target config generated by
// scripts/build-csp.mjs into vercel.json and public/_headers.

// The app's only test seam. `wallet-runtime` resolves to
// components/WalletRuntime.tsx everywhere except a dev server started with
// E2E_WALLET_RUNTIME=1, which gets tests/e2e/support/WalletRuntime.tsx instead.
//
// Deliberately NOT a NEXT_PUBLIC_* variable. Those are inlined into the client
// bundle and are exactly the kind of thing a deploy platform or a stale
// .env.local sets by accident; this one is read here, in Node, at build /
// dev-server start. The consequence is that selecting the E2E wallet runtime
// requires running a different command rather than setting an environment
// variable — a production `next build` cannot reach the mock connector no
// matter what env it inherits.
const useE2EWalletRuntime = process.env.E2E_WALLET_RUNTIME === "1";

const nextConfig: NextConfig = {
  output: "export",
  reactStrictMode: true,
  turbopack: {
    root: path.resolve(__dirname),
    resolveAlias: {
      "wallet-runtime": useE2EWalletRuntime
        ? "./tests/e2e/support/WalletRuntime.tsx"
        : "./components/WalletRuntime.tsx",
    },
  },
  images: {
    unoptimized: true,
  },
};

export default nextConfig;
