import type { NextConfig } from "next";
import path from "node:path";

// Note (R19, R20): this config intentionally does NOT set security
// headers. Next's `headers()` API is a no-op under `output: "export"` —
// real CSP ships as deploy-target config generated by
// scripts/build-csp.mjs into vercel.json and public/_headers.

const nextConfig: NextConfig = {
  output: "export",
  reactStrictMode: true,
  turbopack: {
    root: path.resolve(__dirname),
  },
  images: {
    unoptimized: true,
  },
};

export default nextConfig;
